# Generated by Django 2.2.11 on 2020-03-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('started_by', models.CharField(max_length=30)),
                ('views', models.IntegerField()),
                ('replies', models.IntegerField()),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Category')),
            ],
        ),
    ]
