# Generated by Django 2.2.11 on 2020-03-25 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200325_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('posted_by', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=2000)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 3, 25, 22, 6, 58, 979258))),
            ],
        ),
    ]
