# Generated by Django 2.2.11 on 2020-03-25 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 22, 52, 48, 88010)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 22, 52, 48, 88622)),
        ),
    ]
