# Generated by Django 2.2.11 on 2020-03-26 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200325_2252'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='post',
        #     name='thread',
        #     field=models.ForeignKey(default=forum.models.get_foo, on_delete=django.db.models.deletion.CASCADE, to='forum.Thread'),
        # ),

        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 13, 41, 14, 634719)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 13, 41, 14, 633881)),
        ),
    ]
