# Generated by Django 2.2.11 on 2020-03-29 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200326_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_message',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_to',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 0, 58, 2, 758122)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 0, 58, 2, 757478)),
        ),
    ]
