# Generated by Django 2.2.11 on 2020-03-29 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20200329_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 12, 44, 56, 647016)),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 12, 44, 56, 646354)),
        ),
    ]
