# Generated by Django 3.1.7 on 2021-04-06 15:39

import datetime
from django.db import migrations, models
from django.contrib.auth.models import User 

class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20200403_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 11, 39, 33, 552773)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 11, 39, 33, 551776)),
        ),
        # migrations.AddField(
        #     model_name='post',
        #     name='posted_by_id',
        #     field=models.ForeignKey(
        #         User, 
        #         on_delete=models.PROTECT
        #     )
        # ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField()
        )
    ]
