# Generated by Django 3.1.7 on 2021-04-07 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20210406_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fitness_profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 1, 15, 344028)),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 1, 15, 343031)),
        )
    ]
