# Generated by Django 3.1.7 on 2021-04-07 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0017_auto_20210407_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('fitness_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('body_fat_percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('fitness_goal', models.CharField(choices=[('build_muscle', 'build_muscle'), ('lose_fat', 'lose_fat'), ('improve_sport', 'improve_sport'), ('endurance', 'endurance'), ('flexibility', 'flexibility'), ('other', 'other')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='posted_by_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 11, 35, 58, 665774)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 11, 35, 58, 664777)),
        ),
    ]
