# Generated by Django 3.1.7 on 2021-04-07 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20210407_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='post',
            name='rep_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_to_id',
            field=models.IntegerField(null=True, verbose_name='self'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 15, 51, 23, 465924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 11, 51, 23, 467918)),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 11, 51, 23, 467918)),
        ),
    ]
