# Generated by Django 3.1.7 on 2021-04-07 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20210407_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thread',
            new_name='thread_id',
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 16, 3, 49, 770002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 12, 3, 49, 771001)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 12, 3, 49, 771001)),
        ),
    ]
