# Generated by Django 3.1.7 on 2021-04-08 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_auto_20210408_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 13, 18, 47, 758538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 18, 47, 760531)),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_to_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.post'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 18, 47, 759532)),
        ),
    ]
