# Generated by Django 3.1.7 on 2021-04-08 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_auto_20210408_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 4, 8, 13, 19, 34, 963652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 19, 34, 964650)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 19, 34, 964650)),
        ),
    ]
