# Generated by Django 3.1.7 on 2021-04-11 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_auto_20210410_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 12, 37, 49, 523252, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 8, 37, 49, 524249)),
        ),
        migrations.AlterField(
            model_name='post',
            name='editted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 8, 37, 49, 524249)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 8, 37, 49, 524249)),
        ),
    ]
