# Generated by Django 3.1.7 on 2021-04-18 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0039_auto_20210418_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='latest_post_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 29, 48, 121835)),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 22, 29, 48, 119842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 29, 48, 122857)),
        ),
        migrations.AlterField(
            model_name='post',
            name='editted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 29, 48, 122857)),
        ),
        migrations.AlterField(
            model_name='postsignature',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 29, 48, 123831)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 29, 48, 121835)),
        ),
    ]
