# Generated by Django 3.1.7 on 2021-04-22 00:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0042_auto_20210419_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(to='forum.Tag'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 0, 52, 0, 798319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 52, 0, 800292)),
        ),
        migrations.AlterField(
            model_name='post',
            name='editted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 52, 0, 800292)),
        ),
        migrations.AlterField(
            model_name='postsignature',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 52, 0, 801290)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 52, 0, 799295)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='latest_post_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 20, 52, 0, 799295)),
        ),
    ]
