# Generated by Django 3.1.7 on 2021-04-25 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0043_auto_20210421_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 9, 44, 49, 119146)),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 4, 25, 13, 44, 49, 115156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 9, 44, 49, 117151)),
        ),
        migrations.AlterField(
            model_name='post',
            name='editted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 9, 44, 49, 118148)),
        ),
        migrations.AlterField(
            model_name='postsignature',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 9, 44, 49, 119146)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 9, 44, 49, 117151)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='latest_post_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 9, 44, 49, 117151)),
        ),
    ]
