# Generated by Django 3.1.7 on 2021-05-08 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0049_auto_20210502_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 11, 43, 22, 127177)),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 15, 43, 22, 126180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 43, 22, 129172)),
        ),
        migrations.AlterField(
            model_name='post',
            name='editted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 43, 22, 129172)),
        ),
        migrations.AlterField(
            model_name='postsignature',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 43, 22, 130169)),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 43, 22, 130169)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 43, 22, 128175)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='latest_post_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 43, 22, 128175)),
        ),
    ]
