# Generated by Django 3.2 on 2021-05-09 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0052_auto_20210508_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 21, 21, 39, 954248)),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 1, 21, 39, 953249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 8, 21, 21, 39, 955246)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 21, 39, 956244)),
        ),
        migrations.AlterField(
            model_name='post',
            name='editted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 21, 39, 956244)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forumuser'),
        ),
        migrations.AlterField(
            model_name='postsignature',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 21, 39, 958237)),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 21, 39, 958237)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 21, 39, 955246)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='latest_post_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 21, 39, 955246)),
        ),
    ]
