# Generated by Django 3.2.3 on 2021-05-30 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0053_auto_20210508_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 8, 0, 41, 551966)),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='member_since',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 13, 0, 41, 550044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 8, 0, 41, 553069)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 8, 0, 41, 555016)),
        ),
        migrations.AlterField(
            model_name='post',
            name='editted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 8, 0, 41, 555035)),
        ),
        migrations.AlterField(
            model_name='postsignature',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 8, 0, 41, 556987)),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 8, 0, 41, 558570)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 8, 0, 41, 553566)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='latest_post_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 8, 0, 41, 553583)),
        ),
    ]
